### ISSUE TITLE
keras h5py & hdf5 flags

### ISSUE THREAD

**Issue by LGTrader** [RomaniukVadim/glicOne-overlay#2]
First, thanks for the work on the overlay. I've done an initial install of keras but haven't used it yet. I will report back how it goes.

I am having trouble with the h5py and hdf5 flags. Are these flags known to work or not work? 

I probably only need hdf5 right now but I'm not understanding the emerge messages.

Thanks in advance.

c2RAID6 ~ # emerge -pvDuN keras

These are the packages that would be merged, in order:

Calculating dependencies... done!

!!! The ebuild selected to satisfy "sci-libs/hdf5" has unmet requirements.
- sci-libs/hdf5-1.8.18::gentoo USE="cxx fortran hl threads zlib -debug -examples -fortran2003 -mpi -static-libs -szip" ABI_X86="(64)"

  The following REQUIRED_USE flag constraints are unsatisfied:
    threads? ( !cxx !fortran !hl )

  The above constraints are a subset of the following complete expression:
    threads? ( !cxx !mpi !fortran !hl ) fortran2003? ( fortran )

(dependency required by "dev-python/keras-2.1.5::glicOne[hdf5]" [ebuild])
(dependency required by "keras" [argument])
c2RAID6 ~ #

**Comment by RomaniukVadim** [comment]
Hi, I am glad to hear that. As I see you try to emerge hdf5 package with threads cxx fortran and hl use flags, but emerge said that threads can't be enabled if cxx fortran or hl flags enabled. Try to disable threads, or cxx fortran hl in sci-libs/hdf5 package.

**Comment by LGTrader** [comment]
Thank you. sci-lib/hdf5 -threads seems to have built correctly. I'm just an end-user type so trickier emerge message get past me.

The next issue is finding tensorflow. Can you recommend an overlay with that? I've tried building keras with and without cudnn support but both ways simple keras imports tell me there's no tensorflow backend found.

**Comment by LGTrader** [comment]
NOTE: I can switch to the Theano backend using keras.json but I'd like to work with Tensorflow if possible.

**Comment by RomaniukVadim** [comment]
science overlay have tensorflow ebuild. Also I know keras not well, just write ebuild.

**Comment by LGTrader** [comment]
OK, sadly the science overlay tensorflow ebuild failed here so I've posted a bug report. I'm not a keras expert but have taken a class recently and intend to use it extensively if it works on Gentoo. I can work short-term with theano as a backend. Hopefully someone will address the tensorflow build issues. 
Thanks again for your help.

**Comment by RomaniukVadim** [comment]
You are welcome. Close issue for now.
